name: FakePlayer
version: '${version}'
main: me.chrommob.fakeplayer.FakePlayer
api-version: '1.20'
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
  reloadfakeplayer:
    description: Reloads the FakePlayer plugin
    usage: /reloadfakeplayer
    permission: fakeplayer.reload
    aliases: [rfp]
permissions:
  fakeplayer.reload:
    description: Allows the player to reload the FakePlayer plugin
    default: op
  fakeplayer.exempt:
    description: Allows the player to bypass the FakePlayer plugin
    default: op