name: FakePlayer
version: '${version}'
main: me.chrommob.fakeplayer.FakePlayer
api-version: '1.20'
commands:
    addfakeplayer:
        description: Add a fake player
        usage: /addfakeplayer <name>

    removefakeplayer:
        description: Remove a fake player
        usage: /removefakeplayer <name>
